name: Fetch HW4 Bit Battle Leaderboard

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: hsph-bst236/course-materials
          token: ${{ secrets.GITHUB_PAT }}
          path: source-repo
          
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: current-repo
          
      - name: Copy README file
        run: |
          if [ -f "source-repo/README.md" ]; then
            cp source-repo/README.md current-repo/
            echo "README.md copied successfully"
          else
            echo "README.md not found in source repository"
            exit 1
          fi
          
      - name: Commit and push changes
        run: |
          cd current-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README.md from organization repository" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 