name: Fetch HW3 Bit Battle Leaderboard

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          
      - name: Copy README from organization repository
        run: |
          python -c '
          import os
          from github import Github
          
          # Initialize GitHub client with organization access
          token = os.environ["GITHUB_PAT"]
          g = Github(token)
          
          org_name = "hsph-bst236"  # The organization name
          target_repo_name = "HW4_Bit_process"  # Specific target repository name
          
          try:
              # Get the organization
              org = g.get_organization(org_name)
              print(f"Successfully accessed organization: {org_name}")
              
              # Look for a README in the organization
              org_repos = list(org.get_repos())
              print(f"Total repositories in organization: {len(org_repos)}")
              
              # Try to find a source repo - looking for a likely main repository
              source_repo = None
              for repo in org_repos:
                  if repo.name == org_name or "main" in repo.name.lower() or "course" in repo.name.lower():
                      source_repo = repo
                      break
              
              if not source_repo and org_repos:
                  # If no ideal match found, use the first repo
                  source_repo = org_repos[0]
              
              if source_repo:
                  print(f"Using source repository: {source_repo.name}")
                  try:
                      # Get README content from the source repo
                      readme_content = source_repo.get_contents("README.md").decoded_content.decode("utf-8")
                      
                      # Write to local README
                      with open("README.md", "w") as f:
                          f.write(readme_content)
                      
                      print("README.md updated successfully")
                  except Exception as e:
                      print(f"Error getting README from {source_repo.name}: {str(e)}")
              else:
                  print(f"No repositories found in the {org_name} organization")
                  
          except Exception as e:
              print(f"Error: {str(e)}")
          '
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README.md from organization repository" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 